services:
  app:
    build: .
    container_name: inchi_app
    ports:
      - "8612:8612"
    environment:
      - INCHI_WS_APP_PORT=8612
    # volumes:
    #   - ./app:/app
    # depends_on:
    #   - db
  db:
    image: postgres:15
    container_name: inchi_postgres
    environment:
      POSTGRES_USER: rdkit_user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: rdkit_database
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    command: 
      ["postgres", "-c", "listen_addresses=*"]
    volumes:
      - pgdata:/var/lib/postgresql/data   
volumes:
  pgdata:
